import os

import yaml

from ys import db, paths, procutil
from ys.experiment import load_experiment

DEFAULT_PORT = 4000

# LiteLLM resolves `litellm_settings.callbacks` as a file path relative to the
# config's own directory, not as a Python import. So the callback must be named
# after a real .py file sitting next to the generated config.
SHIM_MODULE = "_ys_shim"
SHIM_SOURCE = '''"""Generated by `ys proxy up`. LiteLLM resolves proxy callbacks as a file
path relative to the config directory, so this shim must live next to the
generated config and re-export the real collector.
"""
from ys.collector import yardstick_logger  # noqa: F401
'''


class ProxyError(Exception):
    pass


def _fallback_params(model_value: str) -> dict:
    return {
        "model": f"anthropic/{model_value}",
        "api_key": "os.environ/ANTHROPIC_API_KEY",
    }


def generate_config(experiment_paths: list[str]) -> str:
    paths.ensure_home()

    model_params: dict[str, dict] = {}
    for path in experiment_paths:
        exp = load_experiment(path)
        for name, params in exp.models.items():
            model_params[name] = dict(params)
        for arm in exp.arms:
            value = arm.factors.get("model")
            if value and value not in model_params:
                model_params[value] = _fallback_params(value)

    if not model_params:
        raise ProxyError(
            "no models resolved from the given experiments -- each arm needs a "
            "`model` factor, or the experiment needs a `models:` block."
        )

    config = {
        "model_list": [
            {"model_name": name, "litellm_params": params}
            for name, params in sorted(model_params.items())
        ],
        "litellm_settings": {
            "callbacks": f"{SHIM_MODULE}.yardstick_logger",
            "drop_params": True,
        },
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }

    config_dir = os.path.dirname(paths.PROXY_CONFIG_PATH)
    with open(os.path.join(config_dir, f"{SHIM_MODULE}.py"), "w") as f:
        f.write(SHIM_SOURCE)
    with open(paths.PROXY_CONFIG_PATH, "w") as f:
        yaml.safe_dump(config, f, sort_keys=False)

    return paths.PROXY_CONFIG_PATH


def proxy_up(experiment_paths: list[str], port: int = DEFAULT_PORT) -> str:
    if not os.environ.get("LITELLM_MASTER_KEY"):
        raise ProxyError(
            "LITELLM_MASTER_KEY is not set. Export a key of your choosing before "
            "starting the proxy, e.g.\n"
            "    export LITELLM_MASTER_KEY=sk-...\n"
            "The same value is what your harness sends as its API key."
        )

    existing = procutil.read_pid(paths.PROXY_PID_PATH)
    if existing and procutil.alive(existing):
        raise ProxyError(
            f"proxy already running (pid {existing}). Run `ys proxy down` first."
        )

    db.init_db()  # the collector writes to this schema from inside the proxy subprocess
    config_path = generate_config(experiment_paths)

    # This environment has no route to github.com, so litellm's startup fetch of its
    # remote model-cost map always fails -- it falls back to its local backup either
    # way, but the failed fetch can eat several seconds of the 15s readiness window.
    os.environ.setdefault("LITELLM_LOCAL_MODEL_COST_MAP", "True")

    pid = procutil.launch_detached(
        ["litellm", "--config", config_path, "--port", str(port)],
        paths.PROXY_LOG_PATH,
        paths.PROXY_PID_PATH,
        paths.PROXY_PORT_PATH,
        port,
    )

    if not procutil.wait_ready(f"http://localhost:{port}/health/readiness"):
        raise ProxyError(
            f"proxy (pid {pid}) did not become ready within 15s. "
            f"Check the log at {paths.PROXY_LOG_PATH}"
        )

    return f"http://localhost:{port}"


def read_port(default: int = DEFAULT_PORT) -> int:
    """The port the currently-configured proxy is (or was last) listening on.

    Used by `ys start` to print the right ANTHROPIC_BASE_URL when `ys proxy
    up` was given a non-default --port.
    """
    return procutil.read_port(paths.PROXY_PORT_PATH, default)


def proxy_down() -> str:
    return procutil.stop(paths.PROXY_PID_PATH, paths.PROXY_PORT_PATH)


def proxy_status() -> tuple[bool, int | None]:
    return procutil.status(paths.PROXY_PID_PATH)
