import json
import os
import urllib.error
import urllib.request

import yaml

from ys import db, paths, procutil
from ys.experiment import load_experiment

DEFAULT_PORT = 4000

# `ys proxy up --backend` (feature: Portkey backend). LiteLLM stays the
# default -- every existing workflow/doc/test that doesn't pass --backend
# keeps behaving exactly as before. "portkey" dispatches to
# ys/portkey_backend.py instead, which points the harness at the caller's
# own hosted Portkey Cloud account rather than a locally-run multi-provider
# router -- see that module's docstring for how (and why) it differs from
# everything below.
BACKEND_LITELLM = "litellm"
BACKEND_PORTKEY = "portkey"
DEFAULT_BACKEND = BACKEND_LITELLM

# Any model id not covered by an experiment's `models:` block or arm
# `factors.model` convention still needs somewhere to go -- Claude Code's
# background/title-generation traffic in particular carries model ids the
# experiment never declared. Without a catch-all, LiteLLM 400s those
# requests and the whole run fails. This passes them straight through to a
# real provider (LiteLLM's provider-wildcard routing: `model_name: "*"` +
# `litellm_params.model: "<provider>/*"`) and the collector still records
# them -- unmeasured against a declared arm, but not a broken run. Which
# provider the catch-all targets is decided by `_catch_all_params` below
# (feature 5 in IMPROVEMENTS.md) -- it used to be hardcoded to Anthropic.
CATCH_ALL_MODEL_NAME = "*"

# Providers with a single bearer-token-shaped credential that LiteLLM reads
# via a plain `api_key` field pointed at one conventional env var name.
# Providers with fundamentally different auth (Bedrock's AWS SigV4
# credentials, Vertex's GCP service-account file, ...) are deliberately not
# listed here: LiteLLM already reads their own standard env vars
# (AWS_ACCESS_KEY_ID/GOOGLE_APPLICATION_CREDENTIALS/...) on its own, without
# needing an explicit `api_key` field in litellm_params -- guessing a
# plausible-but-wrong field name for them would be worse than leaving it out
# (same reasoning ys/harness.py applies to which coding tools it supports).
_SIMPLE_API_KEY_ENV_VAR = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
    "gemini": "GEMINI_API_KEY",
}

# LiteLLM resolves `litellm_settings.callbacks` as a file path relative to the
# config's own directory, not as a Python import. So the callback must be named
# after a real .py file sitting next to the generated config.
SHIM_MODULE = "_ys_shim"
SHIM_SOURCE = '''"""Generated by `ys proxy up`. LiteLLM resolves proxy callbacks as a file
path relative to the config directory, so this shim must live next to the
generated config and re-export the real collector.
"""
from ys.collector import yardstick_logger  # noqa: F401
'''


class ProxyError(Exception):
    pass


def _fallback_params(model_value: str) -> dict:
    """Convention for a `factors.model` value with no explicit `models:`
    entry. An unprefixed value (no `/`) keeps the original, unchanged
    default of assuming Anthropic (`anthropic/<value>` +
    `ANTHROPIC_API_KEY`) -- every experiment written before feature 5 relies
    on exactly this. A value that's already provider-prefixed LiteLLM-style
    (`openai/gpt-4o`, `gemini/gemini-1.5-pro`, `bedrock/anthropic.claude-...`)
    is used as-is instead of being blindly prefixed again -- the pre-feature-5
    code always prepended `anthropic/` regardless, which double-prefixed an
    already-prefixed value into nonsense like `anthropic/openai/gpt-4o`. The
    provider is read straight off that prefix (LiteLLM's own routing
    convention, which the experiment author already had to get right for
    LiteLLM to reach the right backend at all -- not a second, independently-
    maintained "provider:" field that could drift out of sync with it)."""
    if "/" in model_value:
        provider = model_value.split("/", 1)[0]
        params = {"model": model_value}
        env_var = _SIMPLE_API_KEY_ENV_VAR.get(provider)
        if env_var:
            params["api_key"] = f"os.environ/{env_var}"
        return params
    return {
        "model": f"anthropic/{model_value}",
        "api_key": "os.environ/ANTHROPIC_API_KEY",
    }


def _catch_all_params(model_params: dict) -> dict:
    """The catch-all's own provider (see CATCH_ALL_MODEL_NAME's comment for
    why it exists at all). Anthropic was hardcoded here originally because
    every harness this rig drove (Claude Code) only ever sent Anthropic-
    shaped background model ids. Feature 5 adds harnesses that speak other
    protocols (Codex CLI, Aider -- OpenAI-shaped), whose own unregistered/
    background traffic would carry an OpenAI-shaped model id instead --
    routing that through an `anthropic/*` catch-all would send an OpenAI
    model id to the Anthropic API, which is nonsensical.

    LiteLLM only supports one true wildcard `model_name`, so this can't
    branch per request; instead it infers a single provider from the
    experiment's own declared/resolved models -- if every one of them
    agrees, the catch-all matches it. If they don't (a genuinely
    mixed-provider comparison) or none of them are prefixed at all, it falls
    back to the original `anthropic/*` default, unchanged -- still the best
    single guess absent a clearer signal, and exactly today's behavior for
    every experiment that predates this."""
    providers = {
        params["model"].split("/", 1)[0]
        for params in model_params.values()
        if "/" in params.get("model", "")
    }
    provider = providers.pop() if len(providers) == 1 else "anthropic"
    params = {"model": f"{provider}/*"}
    env_var = _SIMPLE_API_KEY_ENV_VAR.get(provider)
    if env_var:
        params["api_key"] = f"os.environ/{env_var}"
    return params


def generate_config(experiment_paths: list[str]) -> str:
    paths.ensure_home()

    model_params: dict[str, dict] = {}
    for path in experiment_paths:
        exp = load_experiment(path)
        for name, params in exp.models.items():
            model_params[name] = dict(params)
        for arm in exp.arms:
            value = arm.factors.get("model")
            if value and value not in model_params:
                model_params[value] = _fallback_params(value)

    if not model_params:
        raise ProxyError(
            "no models resolved from the given experiments -- each arm needs a "
            "`model` factor, or the experiment needs a `models:` block."
        )

    config = {
        "model_list": [
            {"model_name": name, "litellm_params": params}
            for name, params in sorted(model_params.items())
        ]
        + [
            {
                "model_name": CATCH_ALL_MODEL_NAME,
                "litellm_params": _catch_all_params(model_params),
            }
        ],
        "litellm_settings": {
            "callbacks": f"{SHIM_MODULE}.yardstick_logger",
            "drop_params": True,
        },
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }

    config_dir = os.path.dirname(paths.PROXY_CONFIG_PATH)
    with open(os.path.join(config_dir, f"{SHIM_MODULE}.py"), "w") as f:
        f.write(SHIM_SOURCE)
    with open(paths.PROXY_CONFIG_PATH, "w") as f:
        yaml.safe_dump(config, f, sort_keys=False)

    return paths.PROXY_CONFIG_PATH


def read_backend() -> str:
    """Which backend the currently-running (or last-run) proxy is -- read by
    `ys start`/`ys end`/`ys doctor` so they don't have to be told --backend
    again on every command after `ys proxy up`. Defaults to LiteLLM, same as
    `proxy_up` itself, for a proxy started before this flag existed (no
    PROXY_BACKEND_PATH on disk yet) or one started by a caller that never
    passed --backend."""
    if not os.path.exists(paths.PROXY_BACKEND_PATH):
        return DEFAULT_BACKEND
    with open(paths.PROXY_BACKEND_PATH) as f:
        return f.read().strip() or DEFAULT_BACKEND


def _write_backend(backend: str):
    with open(paths.PROXY_BACKEND_PATH, "w") as f:
        f.write(backend)


def proxy_up(experiment_paths: list[str], port: int = DEFAULT_PORT, backend: str = DEFAULT_BACKEND) -> str:
    if backend not in (BACKEND_LITELLM, BACKEND_PORTKEY):
        raise ProxyError(f"unknown backend '{backend}' -- choose from: {BACKEND_LITELLM}, {BACKEND_PORTKEY}")

    if backend == BACKEND_PORTKEY:
        # Deliberately not passed `experiment_paths`: unlike LiteLLM,
        # Portkey Cloud routes by the model string + virtual key at request
        # time rather than a pre-registered model_list, so there is no
        # config to generate up front -- see ys/portkey_backend.py.
        from ys import portkey_backend

        url = portkey_backend.proxy_up(port=port)
        paths.ensure_home()
        _write_backend(BACKEND_PORTKEY)
        return url

    if not os.environ.get("LITELLM_MASTER_KEY"):
        raise ProxyError(
            "LITELLM_MASTER_KEY is not set. Export a key of your choosing before "
            "starting the proxy, e.g.\n"
            "    export LITELLM_MASTER_KEY=sk-...\n"
            "The same value is what your harness sends as its API key."
        )

    existing = procutil.read_pid(paths.PROXY_PID_PATH)
    if existing and procutil.alive(existing):
        raise ProxyError(
            f"proxy already running (pid {existing}). Run `ys proxy down` first."
        )
    if procutil.port_in_use(port):
        raise ProxyError(
            f"port {port} is already bound by a process ys has no pidfile for -- a proxy "
            "started outside ys, a previous run `ys proxy down` couldn't kill, or an "
            "unrelated service. Free the port, or start with a different --port."
        )

    db.init_db()  # the collector writes to this schema from inside the proxy subprocess
    config_path = generate_config(experiment_paths)

    # This environment has no route to github.com, so litellm's startup fetch of its
    # remote model-cost map always fails -- it falls back to its local backup either
    # way, but the failed fetch can eat several seconds of the 15s readiness window.
    os.environ.setdefault("LITELLM_LOCAL_MODEL_COST_MAP", "True")

    pid = procutil.launch_detached(
        ["litellm", "--config", config_path, "--port", str(port)],
        paths.PROXY_LOG_PATH,
        paths.PROXY_PID_PATH,
        paths.PROXY_PORT_PATH,
        port,
    )

    if not procutil.wait_ready(f"http://localhost:{port}/health/readiness"):
        raise ProxyError(
            f"proxy (pid {pid}) did not become ready within 15s. "
            f"Check the log at {paths.PROXY_LOG_PATH}"
        )

    _write_backend(BACKEND_LITELLM)
    return f"http://localhost:{port}"


def model_available(model_name: str, port: int, api_key: str, timeout_s: float = 3.0) -> bool | None:
    """Whether the running proxy has an *explicit* model_list entry for
    `model_name` (as opposed to falling through the `*` catch-all, which
    still works but skips any mock_response/params the experiment declared
    for it). Returns None if the query itself failed for any reason --
    unreachable proxy, a non-2xx response, or an unparseable body -- so
    callers can tell "couldn't verify" apart from "verified and missing"."""
    req = urllib.request.Request(
        f"http://localhost:{port}/v1/models",
        headers={"Authorization": f"Bearer {api_key}"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            data = json.load(resp)
    except (urllib.error.URLError, OSError, ValueError):
        return None
    ids = {entry.get("id") for entry in data.get("data", [])}
    return model_name in ids


def model_check_skipped_message(model: str) -> str:
    """Message for the case where `model_available`'s check couldn't run at
    all, because `ys start` has no `LITELLM_MASTER_KEY` in its own
    environment to query the proxy's `/v1/models` with -- distinct from
    `model_available` returning `False` (verified, and missing) or `None`
    (verified reachability, but the proxy didn't answer). `ys proxy up` and
    `ys start` are commonly run in separate shells, so a shell that never
    exported the key is a first-run scenario, not an edge case (finding 29
    in IMPROVEMENTS.md) -- without this, `ys start` silently skips the
    check finding 3 added and the user proceeds believing a verified proxy
    is serving their model. Factored out here, rather than inlined at the
    one caller, so `ys doctor` (finding 12/feature 4) can print the same
    wording instead of inventing its own."""
    return (
        f"couldn't verify model '{model}' is registered on the proxy -- "
        "LITELLM_MASTER_KEY not set in this shell (the check needs it to "
        "query the proxy's /v1/models). Export the same key you started "
        "`ys proxy up` with to verify."
    )


def read_port(default: int = DEFAULT_PORT) -> int:
    """The port the currently-configured proxy is (or was last) listening on.

    Used by `ys start` to print the right ANTHROPIC_BASE_URL when `ys proxy
    up` was given a non-default --port.
    """
    return procutil.read_port(paths.PROXY_PORT_PATH, default)


def proxy_down(force: bool = False) -> str:
    result = procutil.stop(paths.PROXY_PID_PATH, paths.PROXY_PORT_PATH, force=force)
    procutil.remove_if_exists(paths.PROXY_BACKEND_PATH)
    return result


def proxy_status() -> tuple[bool, int | None]:
    return procutil.status(paths.PROXY_PID_PATH)
